"""Add missing fields to rule_executions table

Revision ID: d1fe5d00c482
Revises: d791cac42f06
Create Date: 2026-01-04 17:42:45.862629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1fe5d00c482'
down_revision: Union[str, Sequence[str], None] = 'd791cac42f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule_executions', sa.Column('rule_version_id', sa.Integer(), nullable=True))
    op.add_column('rule_executions', sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('rule_executions', sa.Column('input_payload', sa.JSON(), nullable=True))
    op.add_column('rule_executions', sa.Column('execution_result', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'rule_executions', 'rule_versions', ['rule_version_id'], ['id'])
    op.drop_column('rule_executions', 'execution_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule_executions', sa.Column('execution_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rule_executions', type_='foreignkey')
    op.drop_column('rule_executions', 'execution_result')
    op.drop_column('rule_executions', 'input_payload')
    op.drop_column('rule_executions', 'executed_at')
    op.drop_column('rule_executions', 'rule_version_id')
    # ### end Alembic commands ###
