"""Initial migration

Revision ID: d791cac42f06
Revises: 
Create Date: 2026-01-04 17:15:58.544415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd791cac42f06'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('initials', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'super_admin', name='role'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('identity', 'transaction', 'geolocation', 'document', name='rulecategory'), nullable=False),
    sa.Column('severity', sa.Enum('high', 'medium', 'low', name='severity'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'draft', name='rulestatus'), nullable=True),
    sa.Column('logic', sa.JSON(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_id'), 'rules', ['id'], unique=False)
    op.create_index(op.f('ix_rules_rule_id'), 'rules', ['rule_id'], unique=True)
    op.create_table('rule_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('claim_id', sa.String(), nullable=True),
    sa.Column('execution_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('severity', sa.Enum('high', 'medium', 'low', name='severity'), nullable=True),
    sa.Column('trigger_reasons', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('decision', sa.Enum('pending', 'fraud', 'legitimate', name='decision'), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_executions_claim_id'), 'rule_executions', ['claim_id'], unique=False)
    op.create_index(op.f('ix_rule_executions_id'), 'rule_executions', ['id'], unique=False)
    op.create_table('rule_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('logic_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_versions_id'), 'rule_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_versions_id'), table_name='rule_versions')
    op.drop_table('rule_versions')
    op.drop_index(op.f('ix_rule_executions_id'), table_name='rule_executions')
    op.drop_index(op.f('ix_rule_executions_claim_id'), table_name='rule_executions')
    op.drop_table('rule_executions')
    op.drop_index(op.f('ix_rules_rule_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
